#!/usr/bin/env node
/**
 * PreToolUse(Edit|Write|MultiEdit|NotebookEdit): protege archivos que un agente NUNCA
 * debe editar a mano. Salir con código 2 bloquea y devuelve stderr al agente.
 */
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

const projectDir = process.env.CLAUDE_PROJECT_DIR ?? process.cwd();

/** @type {{ id: string, test: (rel: string, abs: string) => boolean, reason: string }[]} */
const RULES = [
  {
    id: 'generated-adapter',
    test: (_rel, abs) =>
      existsSync(abs) &&
      readFileSync(abs, 'utf8').slice(0, 2000).includes('GENERATED by scripts/harness/sync.mjs'),
    reason:
      'Adaptador generado del harness. Edita la fuente (docs/harness/roles/*.md o ' +
      'scripts/harness/adapters.mjs) y corre `pnpm harness:sync`.',
  },
  {
    id: 'secrets',
    test: (rel) => /(^|\/)\.env(\.[\w-]+)?$/.test(rel) && !rel.endsWith('.env.example'),
    reason:
      'Los .env contienen secretos locales y no se versionan. Edita el `.env.example` ' +
      'correspondiente y pídele al usuario que actualice su .env.',
  },
  {
    id: 'lockfile',
    test: (rel) => rel === 'pnpm-lock.yaml',
    reason: 'El lockfile lo mantiene pnpm. Cambia package.json y ejecuta `pnpm install`.',
  },
  {
    id: 'generated',
    test: (rel) => /(^|\/)generated\//.test(rel) || /(^|\/)(next-env|expo-env)\.d\.ts$/.test(rel),
    reason:
      'Código generado. Edita la fuente (p. ej. prisma/schema.prisma) y regenera (`pnpm db:generate`).',
  },
  {
    id: 'applied-migration',
    test: (rel, abs) => /prisma\/migrations\/.+\/migration\.sql$/.test(rel) && existsSync(abs),
    reason:
      'Nunca se edita una migración existente (ya pudo aplicarse en otro entorno). ' +
      'Cambia schema.prisma y crea una nueva: `pnpm db:migrate --name <cambio>`.',
  },
  {
    id: 'native-folders',
    test: (rel) => /^apps\/mobile\/(ios|android)\//.test(rel),
    reason:
      'ios/ y android/ se generan (Continuous Native Generation). Configura en app.json o ' +
      'con config plugins.',
  },
  {
    id: 'git-internals',
    test: (rel) => rel === '.git' || rel.startsWith('.git/'),
    reason: 'No se edita .git/ a mano. Usa comandos git.',
  },
];

function main() {
  let input;
  try {
    input = JSON.parse(readFileSync(0, 'utf8'));
  } catch {
    process.exit(0);
  }

  const filePath = input?.tool_input?.file_path ?? input?.tool_input?.notebook_path;
  if (!filePath) process.exit(0);

  const abs = path.resolve(projectDir, filePath);
  const rel = path.relative(projectDir, abs).split(path.sep).join('/');
  if (rel.startsWith('..')) process.exit(0); // Fuera del repo: lo gobiernan los permisos normales.

  const violated = RULES.filter((rule) => rule.test(rel, abs));
  if (violated.length === 0) process.exit(0);

  const lines = violated.map((rule) => `  • [${rule.id}] ${rule.reason}`);
  process.stderr.write(`⛔ Edición bloqueada en ${rel}\n${lines.join('\n')}\n`);
  process.exit(2);
}

main();
