#!/usr/bin/env node
/**
 * Genera los adaptadores del harness desde scripts/harness/adapters.mjs.
 *
 *   pnpm harness:sync    → escribe/actualiza los archivos generados (y borra los obsoletos)
 *   pnpm harness:check   → falla si alguno no coincide con su fuente (corre en pnpm check)
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';

import { AGENTS, SKILLS } from './adapters.mjs';

const ROOT = path.resolve(import.meta.dirname, '../..');
export const MARKER = 'GENERATED by scripts/harness/sync.mjs';
const NOTICE = `${MARKER} — do not edit. Source: scripts/harness/adapters.mjs + docs/harness/roles/. Run \`pnpm harness:sync\`.`;

/** Directorios donde viven archivos generados (para detectar obsoletos). */
const GENERATED_ROOTS = ['.claude/agents', '.claude/skills', '.codex/agents', '.agents/skills'];

const yamlBlock = (text) =>
  `>\n${wrap(text, 88)
    .map((line) => `  ${line}`)
    .join('\n')}`;

function wrap(text, width) {
  const lines = [];
  let line = '';
  for (const word of text.split(/\s+/)) {
    if (line && line.length + word.length + 1 > width) {
      lines.push(line);
      line = word;
    } else line = line ? `${line} ${word}` : word;
  }
  if (line) lines.push(line);
  return lines;
}

function claudeAgent(agent) {
  const tools = agent.claudeTools ? `\ntools: ${agent.claudeTools}` : '';
  return `---\nname: ${agent.name}\ndescription: ${yamlBlock(agent.description)}\nmodel: ${agent.claudeModel}${tools}\n---\n\n<!-- ${NOTICE} -->\n\n${agent.body}\n`;
}

function codexProfile(agent, profile) {
  const instructions = `${agent.body}\n\nProfile note: ${profile.note}`;
  if (instructions.includes("'''"))
    throw new Error(`${profile.name}: el cuerpo no puede contener '''`);
  return `# ${NOTICE}\nname = "${profile.name}"\nmodel = "${profile.model}"\nmodel_reasoning_effort = "${profile.effort}"\n\ndescription = '''\n${wrap(agent.description, 88).join('\n')}\n'''\n\ndeveloper_instructions = '''\n${instructions}\n'''\n`;
}

function skill(entry) {
  return `---\nname: ${entry.name}\ndescription: ${yamlBlock(entry.description)}\n---\n\n<!-- ${NOTICE} -->\n\n${entry.body}\n`;
}

export function buildOutputs() {
  const outputs = new Map();
  for (const agent of AGENTS) {
    outputs.set(`.claude/agents/${agent.name}.md`, claudeAgent(agent));
    for (const profile of agent.codexProfiles) {
      outputs.set(`.codex/agents/${profile.name}.toml`, codexProfile(agent, profile));
    }
  }
  for (const entry of SKILLS) {
    outputs.set(`.claude/skills/${entry.name}/SKILL.md`, skill(entry));
    outputs.set(`.agents/skills/${entry.name}/SKILL.md`, skill(entry));
  }
  return outputs;
}

/** Archivos existentes con el marcador de generado (candidatos a obsoletos). */
function existingGenerated() {
  const found = [];
  const walk = (dir) => {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir)) {
      const full = path.join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
      else if (readFileSync(full, 'utf8').includes(MARKER)) found.push(path.relative(ROOT, full));
    }
  };
  for (const root of GENERATED_ROOTS) walk(path.join(ROOT, root));
  return found;
}

function main() {
  const check = process.argv.includes('--check');
  const outputs = buildOutputs();
  const drift = [];

  for (const [rel, content] of outputs) {
    const full = path.join(ROOT, rel);
    const current = existsSync(full) ? readFileSync(full, 'utf8') : null;
    if (current === content) continue;
    drift.push(current === null ? `+ ${rel}` : `~ ${rel}`);
    if (!check) {
      mkdirSync(path.dirname(full), { recursive: true });
      writeFileSync(full, content);
    }
  }

  for (const rel of existingGenerated()) {
    if (outputs.has(rel)) continue;
    drift.push(`- ${rel}`);
    // Solo borra archivos que ÉL MISMO generó (llevan el marcador).
    if (!check) rmSync(path.join(ROOT, rel));
  }

  if (check && drift.length > 0) {
    console.error(
      `✖ harness:check — adaptadores desfasados (corre pnpm harness:sync):\n  ${drift.join('\n  ')}`,
    );
    process.exit(1);
  }
  console.log(
    check
      ? `✔ harness:check — ${outputs.size} adaptadores al día`
      : `✔ harness:sync — ${drift.length ? drift.join(', ') : 'sin cambios'} (${outputs.size} adaptadores)`,
  );
}

main();
